import { Inter } from "next/font/google";
import "./globals.css";
import MaiNav from "@/components/sideNav/MaiNav";
import { ThemeProvider } from "@/components/themeProvider/themeProvider";
import AuthProvider from "@/providers/authProvieder";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="h-screen flex">
              <MaiNav />
              <div className="pt-20 w-full overflow-y-auto">{children}</div>
            </main>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
